// Generated by CoffeeScript 1.3.3
(function() {
  var leakDetector, runTestWith;

  leakDetector = (require('../common/leak-detector'))();

  runTestWith = require('../common/basic-test-base').runTestWith;

  exports.wd = {
    'basic test': {
      chrome: runTestWith({}, {
        browserName: 'chrome'
      }),
      firefox: runTestWith({}, {
        browserName: 'firefox'
      }),
      'checking leaks': leakDetector.lookForLeaks
    }
  };

}).call(this);
